#!/usr/bin/env python3

import json
import xmltodict
import sys

if len(sys.argv) < 3:
    sys.exit('needs 2 arguments. exiting')

filename = sys.argv[1]
output_file = sys.argv[2]

with open(filename) as xml_file:
    data_dict = xmltodict.parse(xml_file.read())
    xml_file.close()

    json_data = json.dumps(data_dict, indent = '\t')
    with open(output_file, 'w') as json_file:
        json_file.write(json_data)
        json_file.close()

