from PyQt5 import QtCore, QtWidgets


class Ui_addSetNodes_window(object):
    def setupAddSetNodes(self, addSetNodes_window):
        addSetNodes_window.setObjectName("addSetNodes_window")
        addSetNodes_window.setEnabled(True)
        addSetNodes_window.resize(513, 170)
        addSetNodes_window.setMinimumSize(QtCore.QSize(513, 170))
        addSetNodes_window.setMaximumSize(QtCore.QSize(513, 170))
        self.AddSetNodesWindowLayout = QtWidgets.QGridLayout(addSetNodes_window)
        self.AddSetNodesWindowLayout.setObjectName("AddSetNodesWindowLayout")
        self.mainLayout_addSetNodesWindow = QtWidgets.QVBoxLayout()
        self.mainLayout_addSetNodesWindow.setObjectName("mainLayout_addSetNodesWindow")
        self.startingIPLayout_addSetNodesWindow = QtWidgets.QHBoxLayout()
        self.startingIPLayout_addSetNodesWindow.setObjectName("startingIPLayout_addSetNodesWindow")
        self.startingIPLabel_addSetNodesWindow = QtWidgets.QLabel(addSetNodes_window)
        self.startingIPLabel_addSetNodesWindow.setObjectName("startingIPLabel_addSetNodesWindow")
        self.startingIPLayout_addSetNodesWindow.addWidget(self.startingIPLabel_addSetNodesWindow)
        self.startingIPInput_addSetNodesWindow = QtWidgets.QLineEdit(addSetNodes_window)
        self.startingIPInput_addSetNodesWindow.setObjectName("startingIPInput_addSetNodesWindow")
        self.startingIPLayout_addSetNodesWindow.addWidget(self.startingIPInput_addSetNodesWindow)
        self.mainLayout_addSetNodesWindow.addLayout(self.startingIPLayout_addSetNodesWindow)
        self.startingMACLayout_addSetNodesWindow = QtWidgets.QHBoxLayout()
        self.startingMACLayout_addSetNodesWindow.setObjectName("startingMACLayout_addSetNodesWindow")
        self.startingMACLabel_addSetNodesWindow = QtWidgets.QLabel(addSetNodes_window)
        self.startingMACLabel_addSetNodesWindow.setObjectName("startingMACLabel_addSetNodesWindow")
        self.startingMACLayout_addSetNodesWindow.addWidget(self.startingMACLabel_addSetNodesWindow)
        self.startingMACInput_addSetNodesWindow = QtWidgets.QLineEdit(addSetNodes_window)
        self.startingMACInput_addSetNodesWindow.setObjectName("startingMACInput_addSetNodesWindow")
        self.startingMACLayout_addSetNodesWindow.addWidget(self.startingMACInput_addSetNodesWindow)
        self.mainLayout_addSetNodesWindow.addLayout(self.startingMACLayout_addSetNodesWindow)
        self.typeNodesLayout_addSetNodesWindow = QtWidgets.QHBoxLayout()
        self.typeNodesLayout_addSetNodesWindow.setObjectName("typeNodesLayout_addSetNodesWindow")
        self.typeNodesLabel_addSetNodesWindow = QtWidgets.QLabel(addSetNodes_window)
        self.typeNodesLabel_addSetNodesWindow.setObjectName("typeNodesLabel_addSetNodesWindow")
        self.typeNodesLayout_addSetNodesWindow.addWidget(self.typeNodesLabel_addSetNodesWindow)
        self.typeNodesCombobox_addSetNodesWindow = QtWidgets.QComboBox(addSetNodes_window)
        self.typeNodesCombobox_addSetNodesWindow.setObjectName("typeNodesCombobox_addSetNodesWindow")
        self.typeNodesCombobox_addSetNodesWindow.addItem('CORE')
        self.typeNodesCombobox_addSetNodesWindow.addItem('VM')
        self.typeNodesCombobox_addSetNodesWindow.addItem('Docker ')
        self.typeNodesLayout_addSetNodesWindow.addWidget(self.typeNodesCombobox_addSetNodesWindow)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.typeNodesLayout_addSetNodesWindow.addItem(spacerItem)
        self.mainLayout_addSetNodesWindow.addLayout(self.typeNodesLayout_addSetNodesWindow)
        self.buttonsLayout_addSetNodesWindow = QtWidgets.QHBoxLayout()
        self.buttonsLayout_addSetNodesWindow.setObjectName("buttonsLayout_addSetNodesWindow")
        self.setNodesCreateButton_addSetNodesWindow = QtWidgets.QPushButton(addSetNodes_window)
        self.setNodesCreateButton_addSetNodesWindow.setObjectName("setNodesCreateButton_addSetNodesWindow")
        self.buttonsLayout_addSetNodesWindow.addWidget(self.setNodesCreateButton_addSetNodesWindow)
        self.setNodesCancelButton_addSetNodesWindow = QtWidgets.QPushButton(addSetNodes_window)
        self.setNodesCancelButton_addSetNodesWindow.setObjectName("setNodesCancelButton_addSetNodesWindow")
        self.buttonsLayout_addSetNodesWindow.addWidget(self.setNodesCancelButton_addSetNodesWindow)
        self.mainLayout_addSetNodesWindow.addLayout(self.buttonsLayout_addSetNodesWindow)
        self.AddSetNodesWindowLayout.addLayout(self.mainLayout_addSetNodesWindow, 0, 0, 1, 1)

        QtCore.QMetaObject.connectSlotsByName(addSetNodes_window)

        _translate = QtCore.QCoreApplication.translate
        addSetNodes_window.setWindowTitle(_translate("addSetNodes_window", "Add Set of Victim Nodes"))
        self.startingIPLabel_addSetNodesWindow.setText(_translate("addSetNodes_window", "Starting IP Address:     "))
        self.startingMACLabel_addSetNodesWindow.setText(_translate("addSetNodes_window", "Starting MAC Address:"))
        self.typeNodesLabel_addSetNodesWindow.setText(_translate("addSetNodes_window", "Type: "))
        self.setNodesCreateButton_addSetNodesWindow.setText(_translate("addSetNodes_window", "Create"))
        self.setNodesCancelButton_addSetNodesWindow.setText(_translate("addSetNodes_window", "Cancel"))
