from PyQt5 import QtCore, QtWidgets


class Ui_workspace_window(object):
    def setupWorkspaceUI(self, workspace_window):
        workspace_window.setObjectName("workspace_window")
        workspace_window.resize(780, 463)
        workspace_window.setMinimumSize(QtCore.QSize(780, 463))
        workspace_window.setMaximumSize(QtCore.QSize(780, 463))
        self.gridLayout = QtWidgets.QGridLayout(workspace_window)
        self.gridLayout.setObjectName("gridLayout")
        self.mainLayout_workspaceWindow = QtWidgets.QHBoxLayout()
        self.mainLayout_workspaceWindow.setObjectName("mainLayout_workspaceWindow")
        self.workspacesLayout_workspaceWindow = QtWidgets.QHBoxLayout()
        self.workspacesLayout_workspaceWindow.setObjectName("workspacesLayout_workspaceWindow")
        self.workspacesList_workspaceWindow = QtWidgets.QTreeWidget(workspace_window)
        self.workspacesList_workspaceWindow.setObjectName("workspacesList_workspaceWindow")
        item_0 = QtWidgets.QTreeWidgetItem(self.workspacesList_workspaceWindow)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.workspacesList_workspaceWindow)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.workspacesList_workspaceWindow)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.workspacesLayout_workspaceWindow.addWidget(self.workspacesList_workspaceWindow)
        self.mainLayout_workspaceWindow.addLayout(self.workspacesLayout_workspaceWindow)
        self.createWorkspaceLayout_workspaceWindow = QtWidgets.QVBoxLayout()
        self.createWorkspaceLayout_workspaceWindow.setObjectName("createWorkspaceLayout_workspaceWindow")
        self.logoLayout_workspaceWindow = QtWidgets.QHBoxLayout()
        self.logoLayout_workspaceWindow.setObjectName("logoLayout_workspaceWindow")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.logoLayout_workspaceWindow.addItem(spacerItem)
        self.logoLabel_workspaceWindow = QtWidgets.QLabel(workspace_window)
        self.logoLabel_workspaceWindow.setObjectName("logoLabel_workspaceWindow")
        self.logoLayout_workspaceWindow.addWidget(self.logoLabel_workspaceWindow)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.logoLayout_workspaceWindow.addItem(spacerItem1)
        self.createWorkspaceLayout_workspaceWindow.addLayout(self.logoLayout_workspaceWindow)
        self.SDSLayout_workspaceWindow = QtWidgets.QHBoxLayout()
        self.SDSLayout_workspaceWindow.setObjectName("SDSLayout_workspaceWindow")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SDSLayout_workspaceWindow.addItem(spacerItem2)
        self.SDSLabel_workspaceWindow = QtWidgets.QLabel(workspace_window)
        self.SDSLabel_workspaceWindow.setObjectName("SDSLabel_workspaceWindow")
        self.SDSLayout_workspaceWindow.addWidget(self.SDSLabel_workspaceWindow)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.SDSLayout_workspaceWindow.addItem(spacerItem3)
        self.createWorkspaceLayout_workspaceWindow.addLayout(self.SDSLayout_workspaceWindow)
        self.versionLayout_workspaceWindow = QtWidgets.QHBoxLayout()
        self.versionLayout_workspaceWindow.setObjectName("versionLayout_workspaceWindow")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.versionLayout_workspaceWindow.addItem(spacerItem4)
        self.versionLabel_workspaceWindow = QtWidgets.QLabel(workspace_window)
        self.versionLabel_workspaceWindow.setObjectName("versionLabel_workspaceWindow")
        self.versionLayout_workspaceWindow.addWidget(self.versionLabel_workspaceWindow)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.versionLayout_workspaceWindow.addItem(spacerItem5)
        self.createWorkspaceLayout_workspaceWindow.addLayout(self.versionLayout_workspaceWindow)
        self.createWorkspaceButton_workspaceWindow = QtWidgets.QPushButton(workspace_window)
        self.createWorkspaceButton_workspaceWindow.setObjectName("createWorkspaceButton_workspaceWindow")
        self.createWorkspaceLayout_workspaceWindow.addWidget(self.createWorkspaceButton_workspaceWindow)
        self.mainLayout_workspaceWindow.addLayout(self.createWorkspaceLayout_workspaceWindow)
        self.gridLayout.addLayout(self.mainLayout_workspaceWindow, 0, 0, 1, 1)

        QtCore.QMetaObject.connectSlotsByName(workspace_window)

        _translate = QtCore.QCoreApplication.translate
        workspace_window.setWindowTitle(_translate("workspace_window", "Scan Detection System"))
        self.workspacesList_workspaceWindow.headerItem().setText(0, _translate("workspace_window", "Workspaces"))
        __sortingEnabled = self.workspacesList_workspaceWindow.isSortingEnabled()
        self.workspacesList_workspaceWindow.setSortingEnabled(False)
        self.workspacesList_workspaceWindow.topLevelItem(0).setText(0, _translate("workspace_window", "Name 1"))
        self.workspacesList_workspaceWindow.topLevelItem(0).child(0).setText(0, _translate("workspace_window",
                                                                                           "C:/Documents"))
        self.workspacesList_workspaceWindow.topLevelItem(1).setText(0, _translate("workspace_window", "Name 2"))
        self.workspacesList_workspaceWindow.topLevelItem(1).child(0).setText(0, _translate("workspace_window",
                                                                                           "C:/Downloads"))
        self.workspacesList_workspaceWindow.topLevelItem(2).setText(0, _translate("workspace_window", "Name 3"))
        self.workspacesList_workspaceWindow.topLevelItem(2).child(0).setText(0, _translate("workspace_window",
                                                                                           "C:/Documents"))
        self.workspacesList_workspaceWindow.setSortingEnabled(__sortingEnabled)
        self.logoLabel_workspaceWindow.setText(_translate("workspace_window", "LOGO"))
        self.SDSLabel_workspaceWindow.setText(_translate("workspace_window", "Scan Detection System"))
        self.versionLabel_workspaceWindow.setText(_translate("workspace_window", "Version 2022.1.0"))
        self.createWorkspaceButton_workspaceWindow.setText(_translate("workspace_window", "Create New Workspace"))
