test_input = {"name": "ScenarioA",
              "networks":[
                  {"id": "2",
                   "name": "Core",
                   "type": "RJ45",
                   "mac": "aa:aa:aa:aa:aa:aa",
                   "ip": "10.10.10.10",
                   "ip4_mask": "24"},
                   {"id": "3",
                   "name": "Docker",
                   "type": "RJ45",
                   "mac": "aa:aa:aa:aa:aa:ab",
                   "ip": "10.10.10.11",
                   "ip4_mask": "24"}
                  ],
              "devices":[
                  {"id": "4",
                   "name": "Victim1Sub1",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:ac",
                   "ip": "10.10.1.2",
                   "ip4_mask": "24"},
                   {"id": "5",
                   "name": "Victim2Sub1",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:ae",
                   "ip": "10.10.1.3",
                   "ip4_mask": "24"},
                    {"id": "6",
                   "name": "Victim3Sub1",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:ad",
                   "ip": "10.10.1.4",
                   "ip4_mask": "24"},
                   {"id": "7",
                   "name": "Victim4Sub2",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:af",
                   "ip": "10.10.2.2",
                   "ip4_mask": "24"},
                    {"id": "8",
                   "name": "Victim5Sub2",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:1c",
                   "ip": "10.10.2.3",
                   "ip4_mask": "24"},
                   {"id": "8",
                   "name": "Victim6Sub2",
                   "type": "PC",
                   "mac": "aa:aa:aa:aa:aa:1e",
                   "ip": "10.10.2.3",
                   "ip4_mask": "24"}
                  ]
              }